apiVersion: v1
kind: Service
# if required to expose and test externally
metadata:
  name: shopping-cart-external-service
  labels:
    app: shopping-cart-service
  namespace: akka-grpc-projection-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: shopping-cart-service