apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service-svc
  labels:
    app: shopping-cart-service
  namespace: akka-grpc-projection-namespace
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: shopping-cart-service